language: python
python:
  - "3.6"

services: postgresql

env:
  - DJANGO=1.11.3

before_install:
  - export DJANGO_SETTINGS_MODULE="pydms.settings"
  - export PYTHONPATH=$HOME/builds/andela-angene/py_dms
  - export PIP_USE_MIRRORS=true

install:
  - pip install -r requirements.txt

before_script:
  - psql -c "CREATE DATABASE mydb;" -U postgres
  - python manage.py makemigrations && python manage.py migrate

script:
  - python manage.py test -v 2 main/test
